# Generated by Django 3.1.8 on 2021-05-20 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_song_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='genre',
            field=models.CharField(default='rock', max_length=50),
            preserve_default=False,
        ),
    ]
